spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://127.0.01:3306/demo1?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
#        slave_1:
#          url: jdbc:mysql://127.0.01:3306/demo2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
#          username: root
#          password: root
#          driver-class-name: com.mysql.jdbc.Driver
#        slave_2:
#          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#          username: ENC(xxxxx)
#          password: ENC(xxxxx)
#          driver-class-name: com.mysql.jdbc.Driver
#          schema: db/schema.sql # 配置则生效,自动初始化表结构
#          data: db/data.sql # 配置则生效,自动初始化数据
#          continue-on-error: true # 默认true,初始化失败是否继续
#          separator: ";" # sql默认分号分隔符

